### Theme
theme:
  name: material
  logo: logo-512x512.png
  favicon: favicon.svg
  highlightjs: false
  pygments: true
  icon:
    repo: simple/forgejo
  palette:
    # Light mode
    - scheme: default
      primary: pink
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: pink
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  font:
    text: Fira Sans
    code: Fira Code
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate


### Basic information
site_name: $ALTDOC_PACKAGE_NAME (v$ALTDOC_PACKAGE_VERSION)

### Repo information
repo_url: https://codefloe.com/spectral-cockpit/opusreader2
repo_name: spectral-cockpit/opusreader2

### Plugins
plugins:
  - search

### Navigation tree
nav:
  - Home: README.md
  - Reference:
    - Key functions:
      - read_opus(): man/read_opus.md
      - print.list_opusreader2(): man/print.list_opusreader2.md
    - Helper functions:
      - opus_test_dsn(): man/opus_test_dsn.md
  - Articles: $ALTDOC_VIGNETTE_BLOCK
  - Changelog: $ALTDOC_CHANGELOG
  - Code of Conduct: $ALTDOC_CODE_OF_CONDUCT
  - Citation: $ALTDOC_CITATION


### Code highlighting
### Math
markdown_extensions:
  - md_in_html
#   - pymdownx.arithmatex:
#       generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      guess_lang: false
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: !relative $docs_dir  # Relative to docs/ root
  - pymdownx.superfences

# extra_javascript:
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
